name: brevly-infra
description: Infraestrutura AWS do Brev.ly (Pós-Graduação TD 360)
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript